package model

import (
	"time"

	"github.com/google/uuid"
	"golang.org/x/crypto/bcrypt"
	"gorm.io/gorm"
)

type User struct {
	ID           uuid.UUID `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name         string    `gorm:"type:varchar(255);not null" json:"name"`
	Email        string    `gorm:"type:varchar(255);uniqueIndex;not null" json:"email"`
	PasswordHash string    `gorm:"type:varchar(255);not null" json:"-"`     // stored as hash
	RoleID       uuid.UUID `gorm:"type:uuid;not null;index" json:"role_id"` // replaces old Role string
	IsActive     bool      `gorm:"default:true" json:"is_active"`

	CreatedAt time.Time      `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt time.Time      `gorm:"autoUpdateTime" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"` // soft delete

	// Relations
	Role        Role         `gorm:"foreignKey:RoleID" json:"role"`
	Institution *Institution `gorm:"foreignKey:InstitutionID" json:"institution"`
	Student     *Student     `gorm:"foreignKey:UserID" json:"student"`
	Sessions    []Session    `gorm:"foreignKey:UserID" json:"sessions"`
}

func (u *User) BeforeCreate(tx *gorm.DB) (err error) {
	// UUID is auto-generated by Postgres, but setting here is still fine.
	if u.ID == uuid.Nil {
		u.ID = uuid.New()
	}
	return nil
}

// HashPassword sets PasswordHash from plain text
func (u *User) HashPassword(password string) error {
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return err
	}
	u.PasswordHash = string(hash)
	return nil
}

// CheckPassword verifies a password against PasswordHash
func (u *User) CheckPassword(password string) error {
	return bcrypt.CompareHashAndPassword([]byte(u.PasswordHash), []byte(password))
}
